"""empty message

Revision ID: 73a7647e08ea
Revises: 
Create Date: 2026-02-13 09:05:19.664210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a7647e08ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensiklopedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=99), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('ekstension', sa.String(length=20), nullable=True),
    sa.Column('ukuran_file', sa.String(length=20), nullable=True),
    sa.Column('tipe', sa.String(length=10), nullable=True),
    sa.Column('keterangan', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_akses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_page', sa.Integer(), nullable=True),
    sa.Column('akses', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_akses_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_page', sa.Integer(), nullable=True),
    sa.Column('akses', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_bagian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_bagian_api', sa.String(length=10), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_cookie_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cookie', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_code', sa.String(length=100), nullable=True),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('golongan', sa.String(length=2), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=True),
    sa.Column('crud', sa.String(length=1), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=True),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('id_unix', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_unix')
    )
    op.create_table('t_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('tgl_in', sa.DateTime(), nullable=True),
    sa.Column('tgl_out', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('departemen', sa.String(length=100), nullable=True),
    sa.Column('golongan', sa.String(length=100), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('t_absensi')
    op.drop_table('page_counter')
    op.drop_table('m_roles')
    op.drop_table('m_pages')
    op.drop_table('m_employees')
    op.drop_table('m_cookie_api')
    op.drop_table('m_bagian')
    op.drop_table('m_akses_management')
    op.drop_table('m_akses')
    op.drop_table('ensiklopedia')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ensiklopedia_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('judul', sa.String(length=99), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('ekstension', sa.String(length=20), nullable=True),
    sa.Column('ukuran_file', sa.String(length=20), nullable=True),
    sa.Column('tipe', sa.String(length=10), nullable=True),
    sa.Column('keterangan', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_akses_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_page', sa.Integer(), nullable=True),
    sa.Column('akses', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_akses_management_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_page', sa.Integer(), nullable=True),
    sa.Column('akses', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_bagian_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('id_bagian_api', sa.String(length=10), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_employees_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('id_code', sa.String(length=100), nullable=True),
    sa.Column('nik', sa.String(length=10), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('golongan', sa.String(length=2), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_pages_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(length=100), nullable=True),
    sa.Column('crud', sa.String(length=1), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_roles_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_absensi_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('tgl_in', sa.DateTime(), nullable=True),
    sa.Column('tgl_out', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_absensi_history')
    op.drop_table('m_roles_history')
    op.drop_table('m_pages_history')
    op.drop_table('m_employees_history')
    op.drop_table('m_bagian_history')
    op.drop_table('m_akses_management_history')
    op.drop_table('m_akses_history')
    op.drop_table('ensiklopedia_history')
    # ### end Alembic commands ###

