"""empty message

Revision ID: b610f5106965
Revises: 
Create Date: 2026-02-11 22:48:21.526103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b610f5106965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('tgl_in', sa.DateTime(), nullable=True),
    sa.Column('tgl_out', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_absensi')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_absensi_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('bagian', sa.String(length=100), nullable=True),
    sa.Column('tgl_in', sa.DateTime(), nullable=True),
    sa.Column('tgl_out', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_absensi_history')
    # ### end Alembic commands ###

