"""empty message

Revision ID: dcc45db4cbe0
Revises: fc1d1d459f6d
Create Date: 2026-02-16 09:53:25.179457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcc45db4cbe0'
down_revision = 'fc1d1d459f6d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_employees', sa.Column('departemen', sa.String(length=100), nullable=True))
    op.drop_column('m_employees', 'department')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_employees', sa.Column('department', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('m_employees', 'departemen')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_employees_history', sa.Column('departemen', sa.String(length=100), nullable=True))
    op.drop_column('m_employees_history', 'department')
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_employees_history', sa.Column('department', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('m_employees_history', 'departemen')
    # ### end Alembic commands ###

