"""empty message

Revision ID: fc1d1d459f6d
Revises: 73a7647e08ea
Create Date: 2026-02-16 09:19:40.509184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d1d459f6d'
down_revision = '73a7647e08ea'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_lembur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('start_lembur', sa.DateTime(), nullable=True),
    sa.Column('end_lembur', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_lembur')
    # ### end Alembic commands ###


def upgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_lembur_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_history', sa.Integer(), nullable=True),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('start_lembur', sa.DateTime(), nullable=True),
    sa.Column('end_lembur', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=250), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('status_aktif', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_history():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_lembur_history')
    # ### end Alembic commands ###

